import type { SBPACK } from '../types/sbpack';

export const influence: SBPACK = {
  bookId: 'influence-001',
  bookTitle: '影响力',
  coverUrl: '/covers/influence.jpg',
  author: '罗伯特·西奥迪尼',
  description: '社会心理学经典，揭示了六大影响力武器——互惠、承诺一致、社会认同、喜好、权威、稀缺——如何在不知不觉中操控我们的决策。',
  distilledAt: '2026-08-23T10:00:00Z',

  nodes: [
    {
      id: 'inf-k1',
      title: '互惠原则',
      type: 'skill',
      summary: '人类有一种根深蒂固的倾向：当别人给予我们好处时，我们会感到有义务回报。这一原则被广泛用于销售、谈判和人际关系中。关键应用：先给予，再索取。',
      dimension: '关系',
      weight: 5,
    },
    {
      id: 'inf-k2',
      title: '承诺与一致性',
      type: 'skill',
      summary: '一旦人们做出选择或表明立场，就会面临内外压力来保持与该立场一致。登门槛技术（Foot-in-the-door）就是利用这一原理：先获得小承诺，再逐步升级。',
      dimension: '决策',
      weight: 5,
    },
    {
      id: 'inf-k3',
      title: '社会认同',
      type: 'knowledge',
      summary: '在不确定的情况下，人们会参考他人的行为来决定自己的行动。"别人都在做"是最强大的说服力之一。这也解释了从众效应和爆款产品的底层逻辑。',
      dimension: '关系',
      weight: 5,
    },
    {
      id: 'inf-k4',
      title: '喜好原则',
      type: 'knowledge',
      summary: '我们更容易被自己喜欢的人说服。喜好来源于：外表吸引力、相似性、赞美、接触与合作、以及关联性（把自己和好事联系在一起）。',
      dimension: '关系',
      weight: 4,
    },
    {
      id: 'inf-k5',
      title: '权威原则',
      type: 'knowledge',
      summary: '人们倾向于服从权威人物的指示，即使这些指示违背自己的判断。权威的象征（头衔、服装、身份标志）往往比真正的权威本身更有效。',
      dimension: '决策',
      weight: 4,
    },
    {
      id: 'inf-k6',
      title: '稀缺原则',
      type: 'skill',
      summary: '"数量有限"、"即将截止"——当某样东西变得稀缺或可能失去时，我们会赋予它更高的价值。稀缺不仅适用于商品，也适用于信息和机会。',
      dimension: '事业',
      weight: 5,
    },
    {
      id: 'inf-k7',
      title: '固定行为模式',
      type: 'knowledge',
      summary: '人类和动物一样有预设的行为触发器。例如"贵=好"的启发式判断。了解这些自动反应机制是防御操纵和有效说服的基础。',
      dimension: '哲思',
      weight: 4,
    },
    {
      id: 'inf-k8',
      title: '防御与反说服',
      type: 'skill',
      summary: '识别六大武器的使用场景，建立心理防线。核心策略：暂停自动反应，问自己"我是否被操控了？"，区分真实需求与被制造的欲望。',
      dimension: '决策',
      weight: 5,
    },
  ],

  evidences: [
    {
      id: 'inf-e1',
      quote: '一个人靠着硬塞给我们一些好处，就能触发我们的亏欠感。',
      nodeId: 'inf-k1',
      location: '第二章',
    },
    {
      id: 'inf-e2',
      quote: '一旦我们做出了一个选择，或采取了某种立场，就会有发自内心的压力迫使我们与之前的行为保持一致。',
      nodeId: 'inf-k2',
      location: '第三章',
    },
    {
      id: 'inf-e3',
      quote: '我们用来判断某个行为是否正确的依据，就是看别人是怎么做的。',
      nodeId: 'inf-k3',
      location: '第四章',
    },
    {
      id: 'inf-e4',
      quote: '我们总是会答应自己认识和喜欢的人提出的要求，这一点都不奇怪。',
      nodeId: 'inf-k4',
      location: '第五章',
    },
    {
      id: 'inf-e5',
      quote: '在权威面前，我们的大脑会停止独立思考，进入服从模式。',
      nodeId: 'inf-k5',
      location: '第六章',
    },
    {
      id: 'inf-e6',
      quote: '对失去某种东西的恐惧，似乎要比对获得同一种东西的渴望，更能激发人们的行动力。',
      nodeId: 'inf-k6',
      location: '第七章',
    },
    {
      id: 'inf-e7',
      quote: '文明的进步，就是人们不假思索就能做的事情越来越多。',
      nodeId: 'inf-k7',
      location: '第一章',
    },
    {
      id: 'inf-e8',
      quote: '最好的防御不是了解这些武器如何起效，而是识别它们正在被使用的那一刻。',
      nodeId: 'inf-k8',
      location: '第八章',
    },
  ],

  relationships: [
    { source: 'inf-k1', target: 'inf-k2', relationType: '递进组合' },
    { source: 'inf-k3', target: 'inf-k4', relationType: '社交杠杆' },
    { source: 'inf-k5', target: 'inf-k7', relationType: '底层机制' },
    { source: 'inf-k6', target: 'inf-k3', relationType: '组合触发' },
    { source: 'inf-k7', target: 'inf-k8', relationType: '攻防关系' },
    { source: 'inf-k1', target: 'inf-k6', relationType: '策略叠加' },
    { source: 'inf-k4', target: 'inf-k5', relationType: '信任来源' },
    { source: 'inf-k8', target: 'inf-k7', relationType: '认知升级' },
  ],
};
