import type { SBPACK } from '../types/sbpack';

export const richDadPoorDad: SBPACK = {
  bookId: 'richdad-001',
  bookTitle: '富爸爸穷爸爸',
  coverUrl: '/covers/rich-dad-poor-dad.jpg',
  author: '罗伯特·清崎',
  description: '通过对比两位"父亲"的财富观念，揭示了富人与穷人在思维模式上的根本差异，是财商教育的启蒙之作。',
  distilledAt: '2026-08-23T10:00:00Z',

  nodes: [
    {
      id: 'rd-k1',
      title: '资产 vs 负债',
      type: 'knowledge',
      summary: '富爸爸的第一课：资产是把钱放进你口袋的东西，负债是把钱从你口袋拿走的东西。富人买入资产，穷人和中产买入自以为是资产的负债。',
      dimension: '财富',
      weight: 5,
    },
    {
      id: 'rd-k2',
      title: '现金流象限',
      type: 'knowledge',
      summary: '人被分为四类：E（雇员）、S（自由职业者）、B（企业主）、I（投资者）。真正的财务自由来自从左侧象限（E/S）迁移到右侧象限（B/I）。',
      dimension: '财富',
      weight: 5,
    },
    {
      id: 'rd-k3',
      title: '财商教育的缺失',
      type: 'knowledge',
      summary: '传统教育系统教授如何为钱工作，却从不教钱如何为你工作。财商是需要主动学习的第四种基本技能（读、写、算、财商）。',
      dimension: '成长',
      weight: 4,
    },
    {
      id: 'rd-k4',
      title: '老鼠赛跑陷阱',
      type: 'knowledge',
      summary: '大多数人陷入"赚钱-消费-赚更多-花更多"的循环。收入增加但支出同步增长，永远无法实现真正的财务自由。打破循环的关键是先支付自己。',
      dimension: '财富',
      weight: 5,
    },
    {
      id: 'rd-k5',
      title: '让钱为你工作',
      type: 'skill',
      summary: '具体方法：学习投资（房产、股票、债券、创业）、建立被动收入流、利用复利效应。关键是先投资于自己的教育，再投资于资产。',
      dimension: '财富',
      weight: 5,
    },
    {
      id: 'rd-k6',
      title: '克服恐惧与失败',
      type: 'skill',
      summary: '富人与穷人面对风险的态度截然不同。失败是学习过程的一部分——清崎自己经历了多次商业失败才最终成功。关键是控制风险而非逃避风险。',
      dimension: '决策',
      weight: 4,
    },
    {
      id: 'rd-k7',
      title: '公司结构与税务优势',
      type: 'skill',
      summary: '富人通过公司实体合法避税：先赚后税（企业主）vs 先税后赚（雇员）。了解基本的公司法和税务策略是财务教育的重要组成部分。',
      dimension: '财富',
      weight: 3,
    },
    {
      id: 'rd-k8',
      title: '选择的力量',
      type: 'knowledge',
      summary: '"我付不起"关闭了思考，"我怎样才能付得起？"开启了可能性。富爸爸教给清崎的不是具体的投资技巧，而是一种面对问题时的思维方式。',
      dimension: '哲思',
      weight: 5,
    },
  ],

  evidences: [
    {
      id: 'rd-e1',
      quote: '资产就是能把钱放进你口袋里的东西，负债就是把钱从你口袋里取走的东西。',
      nodeId: 'rd-k1',
      location: '第二章',
    },
    {
      id: 'rd-e2',
      quote: '穷人和中产阶级为钱而工作，富人让钱为他们工作。',
      nodeId: 'rd-k2',
      location: '第一章',
    },
    {
      id: 'rd-e3',
      quote: '在今天的世界里，仅仅靠在学校里学到的东西是远远不够的。',
      nodeId: 'rd-k3',
      location: '第三章',
    },
    {
      id: 'rd-e4',
      quote: '问题不在于你赚了多少钱，而在于你能留住多少钱，以及让这些钱为你工作多久。',
      nodeId: 'rd-k4',
      location: '第四章',
    },
    {
      id: 'rd-e5',
      quote: '你的房子不是资产，你的房子是负债。它每个月都在从你口袋里拿钱。',
      nodeId: 'rd-k1',
      location: '第五章',
    },
    {
      id: 'rd-e6',
      quote: '失败是成功的一部分。逃避失败的人也在逃避成功。',
      nodeId: 'rd-k6',
      location: '第六章',
    },
    {
      id: 'rd-e7',
      quote: '富人获得资产，穷人和中产阶级获得负债，只不过他们以为那些负债就是资产。',
      nodeId: 'rd-k1',
      location: '第二章',
    },
    {
      id: 'rd-e8',
      quote: '"我付不起"这句话让大脑停止思考。"我怎样才能付得起？"这句话让大脑开始运转。',
      nodeId: 'rd-k8',
      location: '第一课',
    },
  ],

  relationships: [
    { source: 'rd-k1', target: 'rd-k4', relationType: '因果关系' },
    { source: 'rd-k2', target: 'rd-k5', relationType: '路径指引' },
    { source: 'rd-k3', target: 'rd-k8', relationType: '思维转变' },
    { source: 'rd-k4', target: 'rd-k5', relationType: '解决方案' },
    { source: 'rd-k6', target: 'rd-k5', relationType: '心理基础' },
    { source: 'rd-k7', target: 'rd-k2', relationType: '工具支撑' },
    { source: 'rd-k8', target: 'rd-k3', relationType: '底层理念' },
    { source: 'rd-k1', target: 'rd-k7', relationType: '制度应用' },
  ],
};
