import type { RoundtableSeat } from '../types/sbpack';

export const ROUNDTABLE_SEATS: RoundtableSeat[] = [
  {
    id: 'seat-wealth',
    name: '财富席',
    dimension: '财富',
    icon: '💰',
    persona: '巴菲特',
    linkedBookIds: ['richdad-001', 'wolf-001'],
    description: '从资产配置、现金流和长期价值的角度审视问题',
  },
  {
    id: 'seat-decision',
    name: '决策席',
    dimension: '决策',
    icon: '🎯',
    persona: '查理·芒格',
    linkedBookIds: ['influence-001', 'richdad-001'],
    description: '运用多元思维模型和逆向思维来评估选项',
  },
  {
    id: 'seat-career',
    name: '事业席',
    dimension: '事业',
    icon: '🚀',
    persona: '黄仁勋',
    linkedBookIds: ['wolf-001'],
    description: '从技术趋势、创业激情和执行力的角度分析',
  },
  {
    id: 'seat-relationship',
    name: '关系席',
    dimension: '关系',
    icon: '🤝',
    persona: '卡耐基',
    linkedBookIds: ['influence-001', 'wolf-001'],
    description: '从人际影响力、沟通艺术和社交智慧的角度建议',
  },
  {
    id: 'seat-creation',
    name: '创作席',
    dimension: '创作',
    icon: '🎨',
    persona: '乔布斯',
    linkedBookIds: [],
    description: '从美学、极简主义和产品直觉的角度思考',
  },
  {
    id: 'seat-body',
    name: '身心席',
    dimension: '身心',
    icon: '🧘',
    persona: '纳瓦尔',
    linkedBookIds: ['wolf-001'],
    description: '从身心健康、内在平衡和可持续幸福的角度建议',
  },
  {
    id: 'seat-growth',
    name: '成长席',
    dimension: '成长',
    icon: '📈',
    persona: '瑞·达利欧',
    linkedBookIds: ['richdad-001'],
    description: '从系统性原则、痛苦+反思=进步的角度审视',
  },
  {
    id: 'seat-philosophy',
    name: '哲思席',
    dimension: '哲思',
    icon: '🌀',
    persona: '塔勒布',
    linkedBookIds: ['richdad-001', 'influence-001'],
    description: '从反脆弱、随机性和长期主义的角度思辨',
  },
];
